Repository johanhelsing/bevy_pkv, pull requests merged in 2023-04, with the labels that each got.

#28 Stop using unmaintained gh actions
  .github/workflows/ci.yml
Labels: ci

#31 ci: Split rocksdb and sled jobs
  .github/workflows/ci.yml
Labels: ci

#33 Minor docs fixes
  README.md
  src/lib.rs
Labels: documentation

#34 ci: Add wasm check
  .github/workflows/ci.yml
  Cargo.toml
  benches/inserts.rs
Labels: ci

#36 made set and get take AsRef<str>
  Cargo.toml
  examples/enumkeys.rs
  src/lib.rs
Labels: enhancement
